GET http://localhost:3001/api/fruits

###
POST http://localhost:3001/api/fruits/
content-type: application/json

{"name": "banana","price": "1"}

###
DELETE http://localhost:3001/api/persons/4

###
PUT http://localhost:3001/api/persons/2
Content-Type: application/json

{
  "id": 2,
  "name": "UpdatedName",
  "number": "UpdatedNumber"
}
